services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database_adci
    ports:
      - "5432"
      
  pgadmin:
    container_name: pgadmin
    ports:
      - "8080:80"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###
